[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
django = "<4.0"
django-configurations = "*"
dj-database-url = "*"
django-extensions = "*"
"django-select2" = "*"
gunicorn = "*"
whitenoise = "*"
ipython = "*"
numpy = "*"
scipy = "*"
pandas = "*"
seaborn = "*"
scikit-learn = "*"
matplotlib = "*"
statsmodels = "*"
bioservices = "*"
jsonfield = "*"
jsonpickle = "*"
rpy2 = {version = "*", sys_platform = "!= 'win32'"}
tzlocal = "*"
django-webpack-loader = "==0.7.0"
plotly = "*"
tqdm = "*"
loguru = "*"
jupyterlab = "*"
django-grappelli = "<3.0"

# use the version in github where the .ix problem above has been fixed
clustergrammer = {editable = true, ref = "patch", git = "git+https://github.com/MaayanLab/clustergrammer-py"}

pyMultiOmics = "*"
goatools = "*"
pals-pathway = "*"
xml2dict = "*"
mofax = "*"
neo4j-driver = "==1.7.6"

[dev-packages]

[requires]
python_version = "3"